# Generated by Django 4.2.23 on 2025-08-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Transfer', 'Перевод'), ('Replenishment', 'Пополнение'), ('Debit', 'Списание'), ('Loan_payment', 'Платеж по кредиту')], max_length=15)),
                ('status', models.CharField(choices=[('Completed', 'Успешно'), ('Waiting', 'В ожидании'), ('Error', 'Ошибка')], default='Completed', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='accounts.account')),
                ('to_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='accounts.account')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
