# Generated by Django 4.2.23 on 2025-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Completed', 'Успешно'), ('Waiting', 'В ожидании'), ('Error', 'Ошибка')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Transfer', 'Перевод'), ('Replenishment', 'Пополнение'), ('Debit', 'Списание'), ('Loan_payment', 'Платеж по кредиту')], max_length=20),
        ),
    ]
