# Generated by Django 4.2.23 on 2025-08-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Курс: 1 from_currency = X to_currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия за перевод', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма после конвертации и комисии', max_digits=12, null=True),
        ),
    ]
